ALTER TABLE LABDATABASE.MOTORISTAS DROP CONSTRAINT ESCOLAS_MOTORISTAS_FK;
ALTER TABLE LABDATABASE.PERUAS DROP CONSTRAINT MOTORISTAS_PERUAS_FK;
ALTER TABLE LABDATABASE.ALUNOS DROP CONSTRAINT RESPONSAVEIS_ALUNOS_FK;
ALTER TABLE LABDATABASE.ALUNOS DROP CONSTRAINT ESCOLAS_ALUNOS_FK;

DROP TABLE LABDATABASE.PERUAS;
DROP TABLE LABDATABASE.ALUNOS;
DROP TABLE LABDATABASE.MOTORISTAS;
DROP TABLE LABDATABASE.ESCOLAS;
DROP TABLE LABDATABASE.RESPONSAVEIS;


DROP SEQUENCE LABDATABASE.ESCOLAS_CODIGO_ESCOLA_SEQ;
DROP SEQUENCE LABDATABASE.ALUNOS_CODIGO_ALUNO_SEQ;


CREATE TABLE LABDATABASE.PERUAS(
   PLACA VARCHAR(7) NOT NULL,
   MODELO VARCHAR(90) NOT NULL,
   CAPACIDADE INTEGER NOT NULL,
   CNPJ VARCHAR(14) NOT NULL,
   CONSTRAINT PERUAS_PK PRIMARY KEY (PLACA)
);

CREATE TABLE LABDATABASE.MOTORISTAS(
    CNPJ VARCHAR(14) NOT NULL,
    NOME VARCHAR(90) NOT NULL,
    TELEFONE VARCHAR(16) NOT NULL,
    EMAIL VACHAR(90) NOT NULL,
    CONTA VARCHAR(20) NOT NULL,
    CODIGO_ESCOLA NUMBER NOT NULL,
    CONSTRAINT MOTORISTAS_PK PRIMARY KEY (CNPJ)
);

CREATE TABLE LABDATABASE.RESPONSAVEIS(
    CPF VARCHAR(11) NOT NULL,
    NOME VARCHAR(90) NOT NULL,
    CIDADE VARCHAR(90) NOT NULL,
    BAIRRO VARCHAR(90) NOT NULL,
    LOGRADOURO VARCHAR(90) NOT NULL,
    TELEFONE VARCHAR(16) NOT NULL,
    EMAIL VARCHAR(90) NULL,
    NUMERO VARCHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR(200) NULL,
    CONSTRAINT RESPONSAVEIS_PK PRIMARY KEY (CPF)
);

CREATE TABLE LABDATABASE.ESCOLAS(
    CODIGO_ESCOLA NUMBER NOT NULL,
    NOME VARCHAR(90) NOT NULL,
    CIDADE VARCHAR(90) NOT NULL,
    BAIRRO VARCHAR(90) NOT NULL,
    LOGRADOURO VARCHAR(90) NOT NULL,
    TELEFONE VARCHAR(11) NOT NULL,
    CONSTRAINT ESCOLAS_PK PRIMARY KEY(CODIGO_ESCOLA)
);


CREATE TABLE LABDATABASE.ALUNOS(
    CODIGO_ALUNO NUMBER NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    CODIGO_ESCOLA NUMBER NOT NULL,
    HORARIO_AULA VARCHAR(90) NOT NULL,
    NOME VARCHAR(90) NOT NULL,
    TURMA VARCHAR(10) NOT NULL,
    NATRICULA VARCHAR(20) NOT NULL,
    CONSTRAINT ALUNOS_PK PRIMARY KEY(CODIGO_ALUNO)
    
);


CREATE SEQUENCE LABDATABASE.ESCOLAS_CODIGO_ESCOLA_SEQ;
CREATE SEQUENCE LABDATABASE.ALUNOS_CODIGO_ALUNO_SEQ;


ALTER TABLE LABDATABASE.PERUAS ADD CONSTRAINT MOTORISTAS_PERUAS_FK
FOREIGN KEY (CNPJ)
REFERENCES LABDATABASE.MOTORISTAS(CNPJ)
ON DELETE CASCADE
NOT DEFERRABLE;

ALTER TABLE LABDATABASE.MOTORISTAS ADD CONSTRAINT ESCOLAS_MOTORISTAS_FK
FOREIGN KEY (CODIGO_ESCOLA)
REFERENCES LABDATABASE.ESCOLAS(CODIGO_ESCOLA)
ON DELETE CASCADE
NOT DEFERRABLE;

ALTER TABLE LABDATABASE.ALUNOS ADD CONSTRAINT RESPONSAVEIS_ALUNOS_FK
FOREIGN KEY(CPF)
REFERENCES LABDATABASE.RESPONSAVEIS(CPF)
ON DELETE CASCADE
NOT DEFERRABLE;

ALTER TABLE LABDATABASE.ALUNOS ADD CONSTRAINT ESCOLAS_ALUNOS_FK
FOREIGN KEY(CODIGO_ESCOLA)
REFERENCES LABDATABASE.ESCOLAS(CODIGO_ESCOLA)
ON DELET CASCADE
NOT DEFERRABLE;


GRANT ALL ON LABDATABASE.PERUAS TO LABDATABASE;
GRANT ALL ON LABDATABASE.MOTORISTAS TO LABDATABASE;
GRANT ALL ON LABDATABASE.RESPONSAVEIS TO LABDATABASE;
GRANT ALL ON LABDATABASE.ESCOLAS TO LABDATABASE;
GRANT ALL ON LABDATABASE.ALUNOS TO LABDATABASE;

ALTER USER LABDATABASE quota unlimited on USERS;